name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Released Tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ steps.create_tag.outputs.version }}
          release: true
          body: |
            <a target="_blank" href="https://apps.apple.com/app/vidwall/6747587746" title="Vidwall for macOS">
              <img alt="Vidwall AppStore" src="https://jaywcjlove.github.io/sb/download/macos.svg" height="51">
            </a>

      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "Vidwall {{version:${{ steps.create_tag.outputs.version }}}}"
          description: Set 4K videos as dynamic desktop wallpapers, supporting MP4 and MOV formats.
          keywords: Dynamic Wallpaper,Video Wallpaper,Desktop Wallpaper,4K,MP4,MOV,4K Video,Video Desktop
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/vidwall
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          menus:
            Home: index.html
            Apps: https://wangchujiang.com/#/app
            About: https://wangchujiang.com/#/about
          sideEffectFiles:
            - README.md
            - README.zh.md
            - CHANGELOG.md
            - CHANGELOG.zh.md
            - feedback.md
            - feedback.zh.md
            - terms-of-service.md
            - terms-of-service.zh.md
            - privacy-policy.md
            - privacy-policy.zh.md
          footer: |
            <a href="https://wangchujiang.com/#/app" target="_blank">App</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}          
          EOF
      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

